pipeline:
  build:
    image: androidsdk/android-30
    commands:
      - pwd #bump
      - ./gradlew assembleDebug --stacktrace

#this doesn't work yet:
#https://github.com/woodpecker-ci/woodpecker/issues/687
#when:
  #repo: Freeyourgadget/Gadgetbridge
  #branch: master

